### PR TITLE
Fix address calculation in BSP_LCD_FillRGBRect

### PR DESCRIPTION
**Pull request by Tombana**
This fixes an address calculation in `stm32h7b3i_discovery_lcd.c`

### CODE REVIEW

**Comment by RKOUSTM** [comment]
Hi @Tombana,

First of all, we would like to thank you for your contribution. Could you please give us more details about your problem in order to allow a better analysis of the proposed fix.  Would you also give us more details on how to reproduce this issue? 

Thank you again for your contribution.

With regards,

**Comment by Tombana** [comment]
Hi @RKOUSTM ,

If `USE_DMA2D_TO_FILL_RGB_RECT` is enabled (disabled by default) then `BSP_LCD_FillRGBRect` will produce the wrong result. You can reproduce it by using `BSP_LCD_FillRGBRect` but with `USE_DMA2D_TO_FILL_RGB_RECT` enabled. Instead of a rectangle you get a distorted shape.

The code tries to compute the offset into the buffer, and to compute the offset to `array[y_start + y][x]` it *should* do `(y_start + y) * width + x`  but instead it does `y_start * (width + y) + x`. This is just simple indexing of a 2-dimensional array and the original author probably made a typo here.

**Comment by RKOUSTM** [comment]
Hi @Tombana,

Thank you for your contribution. Your report has been forwarded to our development team. We will get back to you as soon as we have more details. 

Thank you once more for this contribution.

With regards,

**Comment by RKOUSTM** [comment]
Hi @Tombana,

Thank you for your contribution. The issue you pointed out has been confirmed. A bug tracker will be opened internally and the fix will be implemented and made available in future release. 

Thank you once again for your contribution.

With regards,

**Comment by RKOUSTM** [comment]
ST Internal Reference: 104778

**Comment by RKOUSTM** [comment]
ST Internal Reference: 104780

**Review by RKOUSTM — CHANGES_REQUESTED** [review]
Hi @Tombana,

Thank you for your contribution.  In order to merge your pull-request, please apply the same fix for the H7 BSP drivers of the following boards:

•	H7B3I_DISCO
•       H7B3I_EVAL
•	H735G_DISCO
•	H743I_EVAL
•	H745I_DISCO
•	H747I_DISCO
•	H747I_EVAL
•	H750B_DISCO

Thank you once more for this contribution.

With regards,

**Comment by Tombana** [comment]
Hi @RKOUSTM,
I've applied the same fix to the other files as requested.

**Review by RKOUSTM — APPROVED** [review]
Hi @Tombana,

Thank you for this update.

With regards,

**Pull request merged**
