### PR TITLE
load correct SRAM to vector register/ LEDs to show cores are running

### PR DESCRIPTION
**Pull request by m0nka**
### Contributor License Agreement (CLA)
* The Pull Request feature will be considered by STMicroelectronics only after a **Contributor License Agreement (CLA)** mechanism has been deployed.
* We are currently working on the set-up of this procedure.

### CODE REVIEW

**Comment by ALABSTM** [comment]
Hi Krassi,

You closed this pull-request. Shall we understand the issue you pointed out revealed to be inconsistent? Thank you for your answer and sorry for the delay to react on your pull-request.

With regards,

**Comment by m0nka** [comment]
Hey,

I thought you don't want it and this is why i have closed it. I have 2-3 bug fixes, if you guys find useful, i can create new pull requests.

BR

**Comment by ALABSTM** [comment]
Hi Krassi,

We do apologize for the delay we take to answer sometimes. Some periods of the year are more busy than others. No need to create a new pull-request. We can simply reopen this one.

With regards,

**Comment by ALABSTM** [comment]
Hi Krassi,

Would you mind providing more details about the issue you noticed? It seems the changes in you pull-request are a mix between the fix you suggest and some code lines for debugging sake.

Such a description would make things easier to our development teams to analyze your pull-request and provide a feedback.

With regards,

**Comment by m0nka** [comment]
I am sorry, it took you very long to check the pull request, the second push was by mistake. Anyway, the error was incorrect vector table ptr in the startup file (i guess just copied from another project). As the code in the M4 core executes from SRAM, and the vector table is there, you need correct address. Just one line to change:

orig:

SCB->VTOR = D2_AHBSRAM_BASE | VECT_TAB_OFFSET;

new:

SCB->VTOR = D2_AXISRAM_BASE | VECT_TAB_OFFSET;

**Comment by ALABSTM** [comment]
Hi Krassi,

Thank you for your answer. Your request will be forwarded to our development teams. Thank you again and stay safe.

With regards,

**Comment by ALABSTM** [comment]
Hi Krassi,

You issue has been confirmed by our development teams. An internal bug tracker has been created. Thank you for your contribution. Take care and stay safe.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 83548

**Comment by ST-dot-com** [comment]
This pull request has been refused, the <a href='https://cla.st.com'>Contribution License Agreement</a> must be signed.

**Pull request closed without merging**
