### PR TITLE
Fix: value of TEMPSENSOR_CAL2_TEMP depends on Rev (V vs. Y)

### PR DESCRIPTION
**Pull request by peschuster**
According to the datasheet, the temperature for the second calibration value of the temperature sensor was changed from 110 °C to 130 °C with revision V of the STM32H7.

### CODE REVIEW

**Comment by RJMSTM** [comment]
Hello @peschuster 

Thank you for your contribution. Would it be possible to share the reference of the datasheet.

BeST Regards,
Rania

**Comment by peschuster** [comment]
Hello @RJMSTM 

Thanks for taking care of this.

It is mentioned in the following datasheet: https://www.st.com/content/ccc/resource/technical/document/datasheet/group3/01/21/00/39/12/c9/4c/f1/DM00388325/files/DM00388325.pdf/jcr:content/translations/en.DM00388325.pdf

Section 6.3.23 is for revision Y and specifies TS_CAL2 to be the value for 110 °C (page 176).
Section 7.3.23 is for revision V and specifies TS_CAL2 to be the value for 130 °C (page 288).

Unfortunately, this is not mentioned in the migration guide and was only brought to our attention after we opened a support case (see case 00171507).

I assumed all STM32H7 would have the same silicon, but after looking through the datasheets of other variants it looks like this fix might need further refinement to only affect certain STM32H7xxx variants.

**Comment by RJMSTM** [comment]
ST Internal Reference: 147066

**Comment by ALABSTM** [comment]
Hello @peschuster,

Thank you very much for having logged this issue and for this proposal. A fix has just been published [here](https://github.com/STMicroelectronics/cmsis_device_h7/commit/3b6fd841e57a6615709408bed4023f5e369c3459). It will be made available on this repository soon enough hopefully.

As you can see, our development teams preferred to implement the fix at the CMSIS level so that both HAL and LL ADC drivers could benefit from it.

Please allow me to close this pull-request in this case. Thank you again for your contribution and thank you for your comprehension.

With regards,

**Comment by ALABSTM** [comment]
Pull-request reopened as change at CMSIS interface's level reverted. The fix shall be implemented in a different way at the HAL-LL driver's level.

**Comment by TOUNSTM** [comment]
Fixed in abbf9ca1b36c9abdb9339e86f0b7b2f4e79edc35

**Pull request closed without merging**
